### ISSUE TITLE
How to register shortcuts forever?

### ISSUE THREAD

**Issue by Kristinita** [colinta/SublimeClipboardManager#10]
I have written and select text _Sasha Bliss_ → <kbd>Ctrl+Shift+P</kbd> → `Clipboard Manager: Copy to Register` → `a`. Now if I press <kbd>Ctrl+Shift+Super+V, a</kbd>, is inserted the text _Sasha Bliss_.

<kbd>Ctrl+Shift+P</kbd> → `Clipboard Manager: Show Registers` → _Sasha Bliss_ in my `CLIPBOARD REGISTERS`:

```
 CLIPBOARD REGISTERS (1)
========================
a: Sasha Bliss
```

But when I reboot Sublime Text 3, after the <kbd>Ctrl+Shift+Super+V, a</kbd>, nothing happens, and

```
 CLIPBOARD REGISTERS (0)
========================
```

What should I do to all the text has been registered forever, but not before the first restart Sublime Text 3?

Windows 10 Education
Sublime Text 3, Build 3114

Thanks.

**Comment by colinta** [comment]
Interesting, we could add a feature that saves the text to the user folder. Not a feature I've heard people ask for in the past, but I'll look into it. No promises - if you really want this, I'd recommend adding it as part of the creation of the HISTORY module object.

**Comment by Kristinita** [comment]
> I'd recommend adding it as part of the creation of the HISTORY module object.

I apologize, you can tell in more detail how I to make it? Thanks.

**Comment by colinta** [comment]
Actually I think this feature is ill-advised.  Sometimes I have passwords in my clipboard when I open sublime, and I would not want those recorded to disk.

**Comment by Kristinita** [comment]
> Actually I think this feature is ill-advised. Sometimes I have passwords in my clipboard when I open sublime, and I would not want those recorded to disk.

It is possible to introduce the feature of optional, allowing users to disable it.

Thanks.

**Comment by colinta** [comment]
Sure, but I'm not interested in writing this feature. The steps to accomplish it aren't hard, though:

- Find an appropriate place to store files; sublime text has API helpers for this
- Bind an event listener to either application-quit or window-close
- serialize the `HISTORY` variable (json should work!)
- do similar for application start, unserializing the history buffer. 

I don't have the time to implement this for you, but if you start a fork and need help I'd be happy to look at it.
