### ISSUE TITLE
Several enhancements

### ISSUE THREAD

**Issue by mg979** [colinta/SublimeClipboardManager#11]
Hi, I've been working on several enhancements for your plugin. If you are interested, you could make a dev branch, so that I can merge my version there, and you can take a closer look. Changes are many and it's almost a rewrite, that's why I'm suggesting this way of doing it. Tell me if you're interested or if I have to keep this stuff for myself, thanks.

Features include:

### Displaying of current item in history in output panel

Syntax/scheme are inherited from the original view:

![Imgur](https://i.imgur.com/Z8xeKPo.gif)

### Alternatively, in popup:

![Imgur](https://i.imgur.com/Kva558Z.gif)

### Parallel yank list

Not sure if the name 'yank' is appropriate, but it's a parallel list that defaults to auto-pop item and starts from the bottom of the list. It's meant for a use-and-forget copying and pasting of a short sequence of items, keeping the exact order while pasting. By default it's independent from the main list and must be activated via keybinding, with list that switches back to default when yank list has been consumed (check status bar in pic).

![Imgur](https://i.imgur.com/ppBdIEo.gif)

Also with optional automatic disjointing of multiple selections/cursors:

![Imgur](https://i.imgur.com/EsF5RRj.gif)

### Navigate history with panel or popup at cursor position

![Imgur](https://i.imgur.com/8zakSZv.gif)

### Command mode

Commands can be bound to a command mode, to reduce chance of keybinding conflicts.
Several commands (registers, show registers/lists etc) work with an input panel rather than direct keybindings. A popup shows the registered content. Registers and histories can be viewed in a buffer, with syntax highlighting, and a searchable text mode. There's also an option to export registers to a json file, and have them imported at startup (all, or numbers/lowercase letters/uppercase letters only).

![Imgur](https://i.imgur.com/G6LCX9X.gif)

**Comment by colinta** [comment]
I love it!! Especially the “show in popup” and “parallel yank history”, that’s definitely something I do a lot, having the first-in-first-out queue seems great. 

How to proceed... individual prs with each feature would be ideal but I understand that that’s not how code is written, so whatever you’ve got, we’ll make it work. 

Thanks! Make sure you add yourself as a contributor as part of the PR! 😎

**Comment by mg979** [comment]
Thanks. Unfortunately the code as a whole has changed so much that if I had to isolate each feature in individual PRs, it would take days. That's why I suggested that you made a separate branch where you can merge the changes, and take a look. For the next changes I'll make smaller commits, but when I started working on this, I didn't do that, so to separate everything is difficult now.

**Comment by colinta** [comment]
Yup, I get it, not a problem. I’ll try to take a look at things this week.

**Comment by mg979** [comment]
Ok, I'm still fixing a couple of things here and there, and I'd like to improve some behaviours. So, no need to hurry :).

**Comment by mg979** [comment]
Ok I finished I think. I cleaned up most stuff. I added more images above that show some more of the new stuff.

I also added an [example keybinding](https://github.com/mg979/SublimeClipboardManager/blob/test/Example%20(simplified).sublime-keymap) that replicates more or less the old example keybinding (the new one includes more commands and uses ctrl, not super).

**Comment by mg979** [comment]
It's back online. Sorry I thought you weren't interested anymore. More or less it's finished. Keybindings aren't optimal, and I also wonder if it's better to get rid of the command mode. It's optional anyway and all commands can be set up independently.

Also, I'm not sure what the original "paste next/previous" did. There are two different behaviours that do similar things now, these:

```
    { "keys": ["super+shift+v"],          "args": {"previous_and_paste": true},                   "command": "clipboard_manager" },
    { "keys": ["super+alt+v"],            "args": {"next_and_paste": true},                       "command": "clipboard_manager" },
```

or these:
```
    { "keys": ["super+shift+v"],          "args": {"paste_and_previous": true},                   "command": "clipboard_manager" },
    { "keys": ["super+alt+v"],            "args": {"paste_and_next": true},                       "command": "clipboard_manager" },
```

You can see which you like more. The first one selects, then pastes, the second one does the opposite(pastes current, then selects and shows the next one).

**Comment by colinta** [comment]
Ah yeah it'll take me a while to get the code merged in.  It's the `test` branch, right?  I didn't see new commits on your `master` branch.

**Comment by mg979** [comment]
Yes it's all in the test branch.

**Comment by colinta** [comment]
Wow you weren't kidding, this IS a total rewrite!

If the keybindings weren't so different I could just merge in the new code, I like the new features and the use of panels.  I'm not crazy about having the commands combined (what's the advantage with that?), though.  I'll be looking at this for a while, please leave it up! 😃

**Comment by mg979** [comment]
>  I'm not crazy about having the commands combined (what's the advantage with that?)

I'm not sure what you mean, if you refer to the "command mode", I also think it's unnecessary at this point. I'm sure keybindings can be set up to replicate the old behaviours. Personally, I mostly use:

```
    { "keys": ["alt+,"],                  "args": {"previous": true},                             "command": "clipboard_manager" },
    { "keys": ["alt+."],                  "args": {"next": true},                                 "command": "clipboard_manager" },
    { "keys": ["alt+ctrl+,"],             "args": {"paste_and_previous": true},                   "command": "clipboard_manager" },
    { "keys": ["alt+ctrl+."],             "args": {"paste_and_next": true},                       "command": "clipboard_manager" },
```
 and yank commands, they should account for most use cases I think :)

**Comment by mg979** [comment]
Maybe you refer to the main command ClipboardManager that takes many kinds of args? I did it because it was easier to experiment with stuff. I could add "pop", "indent", etc just by passing them as args. Feel free to change what you don't like, though.

**Comment by colinta** [comment]
I was looking at your code this morning – is everything you did pushed to github?  I wanted to copy the syntax highlighting feature that you've got, and some of the "show clipboard on ___" feature (e.g. when going up/down in paste history), but all that code looks the same in your test branch.

**Comment by colinta** [comment]
(I mean it looks the same as what I've got in my branch)

**Comment by colinta** [comment]
OK I was able to pretty much implement the part that I really wanted: showing the current clipboard when browsing clipboard history.  Here's how I did it, I doubt it's very similar to your method, but I really appreciate you sharing your code and ideas here!

**Comment by colinta** [comment]
Oops I forgot to share the link to my changes: 2698480

**Comment by mg979** [comment]
Sorry I didn't answer, I received the notifications just now. It was all in the test branch (save a small change in the settings, but I'm not sure it would apply to what you version). Anyway the important is that you got it working (the part that interested you). I'm messing a bit with vim for now so I won't follow the evolution of this thing :). I'll keep the repo there just in case.
