### ISSUE TITLE
No settings file after installation 

### ISSUE THREAD

**Issue by ldmas** [colinta/SublimeClipboardManager#12]
Hi, 
I've just installed the Clipboard Manager, but it doesn't appear under Preferences -> Package Settings. 
So, how to open the settings file of the package? How to change the keys binding? 
Thank you!

**Comment by colinta** [comment]
There are no settings to change, and to set up key bindings you should look at https://github.com/colinta/SublimeClipboardManager/blob/master/Example.sublime-keymap and copy what you need into your own keybindings.  All my plugins work this way – I don't like plugins that mess with my key bindings.
