### ISSUE TITLE
clipboard_manager_copy does not work @ ST Console

### ISSUE THREAD

**Issue by Enteleform** [colinta/SublimeClipboardManager#7]
I've replaced my default copy & paste hotkeys with ClipboardManager.  For the most part, it works great.  However, If I attempt to copy text from the **`console`** panel; the copy function no longer works.

**Comment by colinta** [comment]
Yeah I don't know why that doesn't work - you can right click to copy text from the console.  I tried to debug this, but couldn't figure it out.
