### ISSUE TITLE
Integrating clipboard manager with sublemacs yank and kill

### ISSUE THREAD

**Issue by excetara2** [colinta/SublimeClipboardManager#8]
I wanted to use this package but have been using `sublemacs` which as you have done re-wrote the copy and paste commands. I like the features you have of showing the history and fuzzy selecting items in the history so I have asked the manager of the package about including or integrating such features to kill and yank. It was something they have wanted to do anyway so are interested.

Any way you see to easily integrate the copy and paste buffers or include other buffers so they work with the fuzzy search?

**Comment by colinta** [comment]
Actually, the fuzzy search feature is *really* easy to add - it's built into Sublime, I just use it to show the history!

Is this the package you're talking about? <https://github.com/grundprinzip/sublemacspro>

**Comment by colinta** [comment]
@grundprinzip I took a glance at things, I think this would be as simple as modifying this command:

```python
class ClipboardManagerChooseAndPaste(sublime_plugin.TextCommand):
    def run(self, edit):
        def format(line):
            return line.replace('\n', '\\n')[:64]

        lines = []
        line_map = {}
        # filter out duplicates, keeping the first instance, and format
        for i, line in enumerate(HISTORY):
            if i == HISTORY.index(line):
                line_map[len(lines)] = i
                lines.append(format(line))

        def on_done(idx):
            if idx >= 0:
                idx = line_map[idx]
                HISTORY.at(idx)
                self.view.run_command('paste')

        if lines:
            sublime.active_window().show_quick_panel(lines, on_done)
        else:
            sublime.status_message('Nothing in history')
```

Instead of using `HISTORY`, I think you can drop in the values in `sbp_registers.registers`.

**Comment by colinta** [comment]
Of course, @excetara2, the fastest way to get this feature in sublemacspro is to write it yourself and open a PR 😉

**Comment by colinta** [comment]
I added some comments to the code snipped above.

**Comment by excetara2** [comment]
Yeah I'd already found that function in your coude and was going to try
myself. But I think one of the issues is the sublemacs is written to allow
the copy and paste for multiple regions as well. It checks to verify before
pasting if the number of regions in the kill ring matches the number
currently selected.

So this makes popping in the killring in place of your history not as
trivial. But I guess you can return just the values in the kill ring that
match the number of currently selected regions. Anyways I'll keep talking
with the package manager and we'll figure it out. Thanks for the comments
but yeah shouldn't be too difficult to add!  Cheers :)

**Comment by colinta** [comment]
Oh that's interesting! I just rely on sublime text to figure that out. I think it's based on new lines in the clipboard - 4 cursors and 4 newlines means it behaves as expected. 

Anyway, I bet it won't be much of a curveball. 😄
