### ISSUE TITLE
Usage Instruction

### ISSUE THREAD

**Issue by daumie** [colinta/SublimeClipboardManager#9]
How is this done "Clipboard Manager must be registered to receive the copy and cut commands, so be sure to assign clipboard_manager_copy to ctrl/super+c and clipboard_manager_cup to ctrl/super+x"

**Comment by colinta** [comment]
I'm away from my computer, but check "Example.sublime-keymap", and put that in your user keymap.

**Comment by colinta** [comment]
I just double checked, and these instructions are right - open `Preferences > Key Bindings` and copy the key bindings you want to use.  At a minimum you should copy:

```json
    { "keys": ["super+x"], "command": "clipboard_manager_cut" },
    { "keys": ["super+c"], "command": "clipboard_manager_copy" },
    { "keys": ["super+v"], "command": "clipboard_manager_paste", "args": { "indent": true } },
```

But to get to benefits of forward/backward, you'll want to bind `next_and_paste` and `previous_and_paste`

```json
    { "keys": ["super+alt+v"], "command": "clipboard_manager_next_and_paste" },
    { "keys": ["super+shift+v"], "command": "clipboard_manager_previous_and_paste" },
```

The "show history" is super useful, and it uses the fuzzy finder so you can search your history:

```
    { "keys": ["super+alt+ctrl+v"], "command": "clipboard_manager_choose_and_paste" },
```

The keys are all up to you, these are just my settings.  I hope this helps!  If you have more questions, please ask.

**Comment by alexfradiani** [comment]
@colinta Is not clear in the README that these bindings need to be manually added. For users unfamiliar with the key bindings feature this might be not so intuitive. Maybe write a small note mentioning that? Your last comment in this issue does exactly that.

**Comment by colinta** [comment]
@alexfradiani Good idea, I added more information to the README.  Helpful?
